version: 1.6.0.{build}
image: Visual Studio 2017
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- ps: >-
    nuget restore

build:
  project: C:\projects\dotfeather\dotfeather\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release DotFeather -OutputDirectory DotFeather/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: DotFeather

deploy:
- provider: NuGet
  api_key:
    # Use encrypt tool
    # https://ci.appveyor.com/tools/encrypt
    secure: nknIyuf45/JACWB2OAWD32oU6HlW4AkkiI974KwKPPkMh3dRHJXsVQVbN/iIUjg/
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
- provider: GitHub
  artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  description: |
    + スクリーンショットを撮影する API を**追加**
    + キャプチャーモードを **追加**
      + キャプチャーモードでは、カレントディレクトリに shot ディレクトリを追加し、全フレームを PNG イメージとして保存します。
      + ffmpeg 等の外部ツールと組み合わせることで、動画作成に役立つでしょう。
    + 起動後からの総フレーム数を取得できる `GameBase.TotalFrame` プロパティを**追加**
    + キャプチャーボードであるかどうかを取得できる `GameBase.IsCaptureMode` プロパティを**追加**
    + `TextDrawable` クラスのコンストラクタで色指定を省略すると透明になってしまう不具合を**修正**
    + `Container` においてソートが本来と真逆に行われる不具合を**修正**
    + `IDrawable.ZOrder` を変更しても反映されない不具合を**修正**
    ----

    + **Add** an API to take a screenshot
    + **Add** a capture-mode feature
      + When it turned on, the engine adds "shot" directory at the current directory, and save all frames as PNG images.
      + It will be useful with third-party tools such as ffmpeg.
    + **Add** a `GameBase.TotalFrame` property that returns total frames since the game launched
    + **Add** a `GameBase.IsCaptureMode` property that returns whether the game is in capture mode
    + **Fix** a bug that `TextDrawable` instances will be transparent when omit the color argument on the constructor
    + **Fix* a bug that `Container` sorts the children in reverse
    + **Fix** a bug that nothing happens when changing `IDrawable.ZOrder`

  auth_token:
    secure: FUlGF4CyRZNM6jaGz2wlmsOIwZt4av2Cxn4lHbi5wU5lim3FixH9ZIhLGDRZftOx
  on:
    APPVEYOR_REPO_TAG: true       # deploy on tag push only
