version: 3.0.0.{build}
image: Visual Studio 2019
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: >-
      nuget restore

build:
  project: C:\projects\dotfeather\src\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release src -OutputDirectory src/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: DotFeather

deploy:
  - provider: NuGet
    api_key:
      # Use encrypt tool
      # https://ci.appveyor.com/tools/encrypt
      secure: 0p+A7xhW2Qex9C3sIr4LXPFBNUCxVd1NPvnKH0Yy6uETIpnSAa5q/DkQtOH9Sy9q
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
    draft: false
    prerelease: true
    description: |
      ## DotFeather v3 Public Beta 4

      ## 仕様変更
      - `IWindow.Dpi` プロパティの名称を `IWindow.PixelRatio` に変更
      - テクスチャ描画用低レベル API を、クロスプラットフォーム対応を視野に入れ仕様変更
        - `TextureDrawer` 静的クラスを廃止
        - `ITextureDrawer` インターフェイスを追加
        - `DF.TextureDrawer` 読み取り専用プロパティを追加
          - テクスチャを扱う標準のエレメントはこれを使うように
          - テクスチャ描画プラグイン開発者はこちらに置き換えるようにしてください
      - 図形描画用の低レベル API を追加
        - `IPrimitiveDrawer` インターフェイスを追加
        - `DF.PrimitiveDrawer` 読み取り専用プロパティを追加
          - `Shape` エレメントはこの API を使うように

      ## バグ修正
      - NineSliceSprite エレメントが描画されない不具合を修正

    auth_token:
      secure: FUlGF4CyRZNM6jaGz2wlmsOIwZt4av2Cxn4lHbi5wU5lim3FixH9ZIhLGDRZftOx
    on:
      APPVEYOR_REPO_TAG: true # deploy on tag push only
