version: 2.9.0.{build}
image: Visual Studio 2019
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: >-
      nuget restore

build:
  project: C:\projects\dotfeather\dotfeather\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release DotFeather -OutputDirectory DotFeather/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: DotFeather

deploy:
  - provider: NuGet
    api_key:
      # Use encrypt tool
      # https://ci.appveyor.com/tools/encrypt
      secure: 0p+A7xhW2Qex9C3sIr4LXPFBNUCxVd1NPvnKH0Yy6uETIpnSAa5q/DkQtOH9Sy9q
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    description: |
      ## 2.9.0

      ### 新機能
      - `Vector.Dot` および `VectorInt.Dot` メソッドを追加し、2 ベクトルの内積を求められるように
      - `Rect` および `RectInt` 構造体を追加

      ### バグ修正
      - タイルマップを破棄するとタイルのリソースも破棄される不具合を修正
      - `Container` に同じインスタンスを多重に追加しようとすると、ハンドルされていない例外をスローする不具合を修正

      ----

      ### New Features
      - Added `Vector.Dot` and `VectorInt.Dot` methods to calculate a dot product of two vectors
      - Added `Rect` and `RectInt` structures

      ### Bug fixes
      - Fixed a bug that tiles are also destroyed when the tilemap is destroyed
      - Fixed a bug that throws an unhandled exception when trying to add the multiple references of the same instance to `Container`.

    auth_token:
      secure: FUlGF4CyRZNM6jaGz2wlmsOIwZt4av2Cxn4lHbi5wU5lim3FixH9ZIhLGDRZftOx
    on:
      APPVEYOR_REPO_TAG: true # deploy on tag push only
