version: 0.7.0.{build}
image: Visual Studio 2017
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- ps: >-
    nuget restore

build:
  project: C:\projects\dotfeather\dotfeather\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build: 
  - nuget pack -Prop Configuration=Release DotFeather -OutputDirectory DotFeather/bin/Release/

deploy:
- provider: NuGet
  api_key:
    # Use encrypt tool
    # https://ci.appveyor.com/tools/encrypt
    secure: nknIyuf45/JACWB2OAWD32oU6HlW4AkkiI974KwKPPkMh3dRHJXsVQVbN/iIUjg/
  artifact: /C:\projects\dotfeather\DotFeather\bin\Release\DotFeather.1.0.0.nupkg/
  on:
    appveyor_repo_tag: true
- provider: GitHub
  artifact: /C:\projects\dotfeather\DotFeather\bin\Release\DotFeather.1.0.0.nupkg/           # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  auth_token: 
    secure: FUlGF4CyRZNM6jaGz2wlmsOIwZt4av2Cxn4lHbi5wU5lim3FixH9ZIhLGDRZftOx
  on:
    APPVEYOR_REPO_TAG: true       # deploy on tag push only